name: Publish On NPMJS

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Discard Uncommitted Changes
      run: git reset --hard

    - name: Build theme
      run: npm run build

    - name: Get current version
      id: get_version
      run: echo ::set-output name=version::$(node -p "require('./package.json').version")

    - name: Bump version
      id: bump_version
      run: |
        npm version patch -m "Bump version to %s"
        echo ::set-output name=new_version::$(node -p "require('./package.json').version")
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_DEPLOY_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.ADOBE_GH_TOKEN }}
        GH_TOKEN: ${{ secrets.ADOBE_GH_TOKEN }}

    - name: Update package.json
      run: |
        new_version="${{ steps.bump_version.outputs.new_version }}"
        echo "Updating package.json to version $new_version"
        sed -i "s/\"version\": \".*\"/\"version\": \"$new_version\"/" package.json

    - name: Commit and push changes
      run: |
        git config --global user.email "ci-build@aemforms"
        git config --global user.name "ci-build"
        git add package.json
        git commit -m "Bump version to ${{ steps.bump_version.outputs.new_version }}"
      env:
        GITHUB_TOKEN: ${{ secrets.ADOBE_GH_TOKEN }}
        GH_TOKEN: ${{ secrets.ADOBE_GH_TOKEN }}

    - name: Publish to npm
      run: |
        npm publish --access public
        git push origin HEAD:main
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_DEPLOY_TOKEN }}
